TASK_TYPE: train_e2c_entrance
ENABLE: true
use_ema: false
num_workers: 6
frame_lens: [16, 16]
sample_fps: [8,  8]
resolution: [256, 256]
vit_resolution: [224, 224]
ecgcmr_dataset: {
    'type': 'ECGCMRDATASET',
    'data_path': '/mnt/data2/ECG_CMR/train_data_dict_v8.pt',
    'resizeshape': 256,
}
ecgclip: {
    'type': 'ECGEncoder',
    'pretrained': "/mnt/data2/dingzhengyao/work/checkpoint/preject_version1/output_dir/10002/checkpoint-45-loss-1.53.pth"
}

UNet: {
    'type': 'UNetSD_T2VBase',
    'in_dim': 4,
    'y_dim': 1024,
    'upper_len': 128,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'default_fps': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'misc_dropout': 0.4,
    'temporal_attention': True,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_sim_mask': False
}
Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', # cosine
    'schedule_param': {
        'num_timesteps': 1000,
        'init_beta': 0.00085,
        'last_beta': 0.0120,
        'zero_terminal_snr': False,
    },
    'mean_type': 'eps',
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.0
}
batch_sizes: 3
visual_train: {
    'type': 'VisualTrainECGToCMR',
    'partial_keys': [
        ['y'],
    ],
    'use_offset_noise': False,
    'guide_scale': 9.0, 
}

Pretrain: {
    'type': pretrain_specific_strategies,
    'fix_weight': False,
    'grad_scale': 0.5,
    'resume_checkpoint': '/home/dingzhengyao/Work/T2Vdiff/VGen/workspace/experiments/e2c_train/checkpoints/non_ema_00273000.pth',
    'sd_keys_path': 'data/stable_diffusion_image_key_temporal_attention_x1.json',
}

chunk_size: 5
decoder_bs: 5
lr: 0.00003

noise_strength: 0.1
# classifier-free guidance
p_zero: 0.1
guide_scale: 3.0
num_steps: 281000

use_zero_infer: True
viz_interval: 200        # 200
save_ckp_interval: 500   # 500

# Log
log_dir: "/mnt/data2/dingzhengyao/work/checkpoint/ECG_CMR/diffusion/experiments/"
log_interval: 1
seed: 8888
